apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:32dTSNmX4iMOcNn91YzXUka4+biXsZi073ZFj7h8SACzer33KqevCQ==,iv:hOS+n1zy/auC/z9bSBic6eVvjWW0HuWxF+gjWtKpWu4=,tag:u0WIpS5g7aSc4nPHDAPfVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadDF3SCtMVDMyTmR2bk0x
            cjBPYTZBOU4xMVo2dlZNbTVsYVBtNHNJUjAwClphN0hRc3QwczhuY09sK0xhNXVG
            MURKNEd3RHNDeU9ueWlPYVhXbWNCOGMKLS0tIDh4UFUvcVpiRGFrQWxITENBVDlT
            YWk5S0FPdC9RQUJGQU1SMDlSeEtJakkKR+DflJb/ClpCoIklxmUm/2NC1qqsaYep
            C/YeAabUR6q7gEMQp3kWSpFBtNocYVSsjCXHSNHVCUdlaBuB4TEMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-06T18:05:33Z"
    mac: ENC[AES256_GCM,data:fpq/xF+gxF/g+qfDSJRCtCWxcL7AnSR5nolNjoIEbmRybK6OKWrL/8bEAjK3YjMQ9PnOYSZQaP5HXfurP6d3NojuG+YGPObcHpBYYobFcmfO73jtAf9xdphrt2r7HDlnGKvXph9qm9td4WCYhjZy+IWCMH/PY0YOJjvl4UrZH+4=,iv:jxZ5uYHIzECVJxarNDzIfA9T354U3kQH4x8yLk3Fe0U=,tag:wJobDYITXqHovIFoCyr1iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
