---
kubernetes:
  children:
    master:
      hosts:
        server-pc:
          ansible_host: 192.168.102.2
    worker:
      hosts:
        tv-server:
          ansible_host: 192.168.102.205
        mini-pc:
          ansible_host: 192.168.102.235
