---
kubernetes:
  children:
    master:
      hosts:
        server-pc.lan:
          ansible_host: 192.168.102.2
    worker:
      hosts:
        tv-server.lan:
          ansible_host: 192.168.102.205
