apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ODJTrNnCSnzJlatlvwyfsPnVdT8I6p+dWC2k/EEcf4sMdAkflg==,iv:a/ddgvUBbGPIGoNSJXWWk5u2q0pJDSrdQiRKFqZnXGk=,tag:nCNaYK2BpnIi+eRmuMIg4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQm1oN2RMZjZ2Q3ZmQkhi
            U1RJT1RoczU0Q2FmV2k1Vy90ZEdnYmZSYTA0Ck5sbmM2VTFiTklvN0k1Z014L1p1
            OXNjbXBySjZvSG5xd3A1ekt2TzlYbEUKLS0tIDMwVTBHNE1OMU9VUVRIQ0NSazNH
            cXBzQUNIZ2FITDA3RFB6VnptUS8vVm8K4vGqbJS+qO9utCHl1if1u5hVnHjcri9J
            KXRBDFEWIQo3KZz9uMXRCjZ0/NRbvw+pMbSKyZ5tXgEWtJU8xcNsIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-05T06:32:53Z"
    mac: ENC[AES256_GCM,data:cDROv8vs3HmQixd2OjlIfycjf4WHusWSkmOKKvv4iVKVLGO6Lq6JM3U+chcX3XTY/bjXAkGfW5y1nIskI47EhKZIJYke8rUwkfJlq9B86FZvjjW2ZjOTRPLVWel5iwUF11XyZlcslnVrqt9Nsh5j15E+dD4cELGwGXSO+U56pao=,iv:kRrf9gnr7A9YBXTH5NII+faOrNHo8ptKf1LDRJet/go=,tag:FtbupmtL6+xVATQEeobYUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
