apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:03U9L+85VwS+woruMyxDTk3Mh5K3A+iwHUwIWTm2za53/eMKDA==,iv:B7MCngapNzFG10dB79xsCWDAA/qz/a58D44NLPEaXxQ=,tag:S5HDC0HByeyG5I1PKlgGlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNERWcXdBZGNHV2FJRUs4
            VEh4RUJ0b3dzbUE1MXpaeU5xWWxCbmliMTM0CmpBOEwrVG5lUEZvZkFDWUxXc21T
            cFV4WVA3QWZtbTc0UG5aZ3dzbjIyUk0KLS0tIGR3UVg0MXI4SzBVNHRDMlN3aDFx
            TjBQUGFoL1VYZmNIRnQyd1MzTGgrdTQKjBoVurYZ4f6L6m1EVXQ4fIiCDdNBZmc5
            yyc3o1h0mLjAAsKnQdf2Si7zsG9vApwAfi3QoqPRwiQCE/YOOTpmXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T20:35:54Z"
    mac: ENC[AES256_GCM,data:A6dZdyTng68lnv8aS7cBkR1kI8xFnSpF3+6VUri71dmRG/FBmBcpivYk3/Na/B+Y5kHqyqTN9dZ/biq1LzPWjRL2v5aDw6yM5x3Q32KlSdNaqqVdPIvb4e4e2XKnJpXebp/nb6I9GED1SO3da+7n6bEFP6r7SlPQIBDHYTqfxZI=,iv:QvLBuO12m3vwlBhSH8GseRC9GdypNracYOz4DBbK+EU=,tag:h4hNWukt/Df4k0jRGL/r0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
