apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:4oVOa8KadSO5EFxCaWhLWmUHdmaS8+us/Gfi/AgkFy1qhNV0Pg==,iv:AQpZwikQn3zL6DAO7xVmTB/zyPrckJeY7BFX9cwLXx4=,tag:Oj9yCg7rWKlgyMrJqIYA9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanVUN1BsMkMybG0xZm1T
            dkkxL0tvTmo0aXZHMjJGQUdpN1lYdEY5K2djCk8yYVdpV1NkT0d6TUFMNFMyMFc2
            SG1DVCtJRjhBT3FkZFZQVi9Zc1JQS00KLS0tIC9GUG9WQ3F2TVdMVUpwR0I2QmJL
            dXQ1UmpZUmpGT0RmQ2I1Mll0b3JBR3MKLMtYrC9RDr5hCA2Ywruu8Rw1qvXquT8y
            n/7q7ofyqifCXf2fmQGraQDo+JQU1TmIbuqE+DodJF9W7ellDhxE5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T13:44:04Z"
    mac: ENC[AES256_GCM,data:wZ6HkAlCXfc2/g9fbQHCOavBCV0aQAmLjVB/9CZJrj58cghcPWlfb3ncaoKUo4GBhrUn/qRkclgVfMBZlIXf1Ab6Zh+0Xe8SLNCrTFoE315Mxa+yW448SJqjifgyP5IlhPrAa4ZIeHH5+8pHZsY8+a9h55AwXXFfZYIqNntS4G0=,iv:sZdD2A+ARbHI9Tymqk9Jvu+8Ilk2iq8IN11TMO0uEsM=,tag:S3QjSv7Vw9JiuUrYY3kY/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
