---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-config
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
