---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 12.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    postgresqlUsername: ${SECRET_POSTGRES_USERNAME}
    postgresqlPassword: ${SECRET_POSTGRES_PASSWORD}
    postgresqlDatabase: postgres
    auth:
      username: ${SECRET_POSTGRES_USERNAME}
      password: ${SECRET_POSTGRES_PASSWORD}
      database: postgres
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    persistence:
      size: 5Gi
      existingClaim: postgresql-config
