apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: default
type: Opaque
stringData:
    SECRET_POSTGRES_USERNAME: ENC[AES256_GCM,data:Q0VVjdJVmDc=,iv:JpExUjvpZq6Qy6k0eG7GD2sv0rzP8xPkvYMf1Hcwy+w=,tag:kdqNH9cRuBxoJpqF1zX4Kg==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:mhs26ui1kq2ALKngdBEXkE0T,iv:hTqYBm6guSDb9llHadus29PGozis2a5eUBiqg7ma+do=,tag:HHIgGkEqCB30ux4OKyvA2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WnkydXgxa1NaTzJ6M2VN
            Q0ZkT1doZm82VzNNMk1lQUh5U0VsNVo5d2k4CkExc2dlSWRiUUV2M0RVdXE4Mytm
            Uyt4dnV0aU9EZ0pLTzhlblJ0bjZXQUkKLS0tIDcyVFRYT2VNSUJiLzgrSXRLaCti
            cHp5OHRHOHVyaW1vK0RSVmdsUlVGekEKxkBHH75iS8WkYYS40MIJjuN84JUblctp
            H/1c+vuce5VIRLBLlqAAZ61bkiK5ia1xdreP4TRVbyNSyr/VMNU+Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:34:35Z"
    mac: ENC[AES256_GCM,data:+Jg0y5r1qhYXoGqGXJonZ5SrMBvgJqY7nd0xR4NJrllVUw1JXYf5XIpG9XAQxjTkTYHHyBnFOUTzqDiLhKGPrka1GwOO7a7gT5yRC47vI2+cBFsHJzHfBvDFhbfjwU0yTjD+UcxsIOdYMlHoR5DBRg/fPfob72y2C66R2Z6Jf2U=,iv:4p1QtT38znNW7msm2tEnIqSB0ESvxZTOxtR/5TYI9UQ=,tag:EtqaFDFkmdM2OO/AnH7ITg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
