---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${LOCAL_DOMAIN}-self-signed"
  namespace: networking
spec:
  isCA: false
  duration: 43800h # 5y
  renewBefore: 360h # 15d
  commonName: "${LOCAL_DOMAIN}"
  dnsNames:
    - "${LOCAL_DOMAIN}"
    - "*.${LOCAL_DOMAIN}"
  secretName: "${LOCAL_DOMAIN/./-}-tls"
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: cluster-issuer-from-ca
    kind: ClusterIssuer
    group: cert-manager.io
