apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:r1eh+/Y6qwxZ73OE3S60vvuEY7+5h+MwXBtI5e3/cFwZ69Eh9Ria6VJTDknMCvUxVXeeQ6KEY3fuoWbI,iv:1pkIGAOGThMEIuS9iyQ1gFF4IVkPLSzfDIouBkQFNjk=,tag:pswVFshZ9Fk4+sP6SCKUgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdHFGM1MyL2lINFdwZTZW
            OVRaSkdVZUNFK3BpQlpxZWJJNjZLY0VMQ2pnCldTUks3TjdOeVk1NUZ5d0JBbGND
            VEZQUUZBekpkL2dtdHJTNWcwNTZlWTgKLS0tIHczS1h6Q3c4N0lpQzA2Vk5UaHMx
            ZGh2SVRVdFBMenEwbFJ3TUFBTFFTajgKbstfUC+8U44dFqSDlTF6YgRawKHy+fIg
            YcWGW8ZeKz2OlYhhJLdpLpN1o7+g30Szzr2RyVojhnbX5GoUzgn+1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T13:44:06Z"
    mac: ENC[AES256_GCM,data:hydRlfm8XVfvGX3qxEPZw0C1JLs+PlXOL9v4onJndGzHug6uuTlcCoOevXXjB2gv5TL/spjdahiCuOFgrF7fnlRh29/ICJngE0+GTnZjIYnQ1Mjh8Cg40FN36SrdPkoL9s9inbA8He4tsA09AXOfuSP5PzfSYCUM5Nv5NWNZ0d8=,iv:6CgmBEzAEzjRhpxwPY/8JjVYtYuhXMt4prx7vusrPtQ=,tag:SU/UfLd+amQbnkYyR2ei/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
