---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvheadend-config-v2
  namespace: storage
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
