---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvheadend-config-v7
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
