---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tvheadend
  namespace: media
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/tvheadend
      tag: 4.3.9945@sha256:5d34a66091c199d1f821dc171f946e9ea6eb5086d8ed704def3f6b3346fdfcc3
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: 9981
          htsp:
            port: 9982
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "false"
          hajimari.io/icon: "television"
          hajimari.io/group: "media"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            send_timeout 100m;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        hosts:
          - host: &host-local "tvheadend.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: &host "tvheadend.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      seLinuxOptions:
        level: s0
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      dvb:
        enabled: true
        type: hostPath
        hostPath: /dev/dvb
      # recordings:
      #   enabled: true
      #   existingClaim: media-v2
      #   mountPath: /recordings
      # timeshift:
      #   enabled: true
      #   type: emptyDir
      #   mountPath: /timeshift
    resources:
      requests:
        # gpu.intel.com/i915: 1
        cpu: 100m
        memory: 20Mi
      limits:
        # gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1096Mi
