apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cc6d6I0G/05u6j8GNA==,iv:aFQOt4LOPuU+wzcz+tQtmkcrTKQo+pX2f4vryrovl2k=,tag:OulpuL1ayal7WnK5C79EMw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3DX0GpIvveQNQOXX0UIGWfMnilNObTqJ,iv:azaRlHT3ieT36ZqbIXQ0wL57SRHDVbCbwxRHhRbKEeY=,tag:BYBQdQX15hXPVbBmAo4OXQ==,type:str]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:IK8Vm22kNC+reP7/LA==,iv:hfSgrA9iiipVKbD8S9eFSPfy703v++zNG9IFgcoPj2Q=,tag:3g1OACXvmntZE2mxpp5QzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlODlTTFpVZFBaSnBDVGto
            UlhvM1Ntd3lVS1dCWCtqNTVsejVGK3EwVG1rClpCT1FiaGlaNCtYU3U2c2p5K3BE
            bVBubkVpRnJmNmY4WHFXNGZENklJRTAKLS0tIDhMRG5uN0hoMnpTTGQ4blZGNXVW
            YmhtZTFXWDBhVytIS0hGOG9pV2pIZFUKspKPvmDBMCWXtBYtQ9u8U7PxmS8MOevc
            ksExQPCzz+AS5xO62w1CVpt8kBR7U9LOQ/W3OmGLSATc4ws/XkC/WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T15:36:26Z"
    mac: ENC[AES256_GCM,data:lZYIOAcmws6UuvrID9J7uXTvxbnYQnW8485Hvfbm6sWuU9AFWvdAdZspbterEpCByp+nTDXoqYf4szk90c/0Mq7b/vRTG5Yr/Yk2piyAdQAjAhF4f+rCpJNBgdJz5JLT8EqTHrNGoywwNHDMa8dWo18FVgMilH7kfQU7x7RvT68=,iv:XSpGB7fRN4rNWYYgmNNkwAVIf82XZvZTz+CYXJPJ448=,tag:2Ju2soGgIvs+/OT3t3woeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
