apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: default
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:21VjzxPwF3g50Fq8Dsu8kzLIxWUsGIkblBOsKXeI,iv:9CyMfD7xc0QPatf5Hv064K9iOHN9O9rdJ9r6CF4giA8=,tag:aJOaN+HGYjh9Yhw0DlGP+A==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:O/s7t8DnwyAn6M0=,iv:4+RQgusgicrpgu6TN8zXrihkPIqIx6oETf4G/WFC9hk=,tag:udUkcla+6cUzhIXvBxXKeA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:xlAlWj3beFhsqsWIlqNlcr/627GNRJx1tmaHt//u,iv:8fTByyGF5d4+WBbTrHLAYElbeCkOhIXwlrhnivl+X7w=,tag:5vpXN04YroJHNnFEOeKzFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucwgq79cuef750zcj9xl0j6w5yq9pz3kj96htc54n0v48335egds6s3ysy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdDg4RDNYQ2hYaFJFSVlJ
            dHNYMlh6emdvRjM1bjcwbEpDUTAxNHpTcldRClYrSjBZQjhQUFZqTWNuTlZSL0xH
            ZjBJcXhOaGliQmRkcEJxNnR2bjhYWncKLS0tIFNmUHcwaDAwV0JUS1ltMy9lZlZ1
            S1kxMmpVMDlMMkl3OWYrZmV0Sml0bjgK89W0ZiOH6oEhu4ihIjLHKwSYKpr9zi1O
            YZxajctP6auP/HMmcscNXy6TQ5J848UnC11MWKhE0wZXUaI/IziBKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T15:52:33Z"
    mac: ENC[AES256_GCM,data:eEaklU4dopb/YprUydCuU8wJS2fBtO628uIOsbK6KU3tWV9LS9/2n4DuCBb9Qr7zcmHxVeClRla+RbuEKYxtGYi9z8GjtcyZHRFhepo+saSh6le+sKvHuRnK9PqO5su3S3y7omGaSKWH9KYbrC/0aTzhMskeZ1oCCrh3ybL3NPU=,iv:G1Fe4qPT9f470EV5QreakWFKtuAPvGcHKdYmgMKXCdw=,tag:N1sMtxEp0K4LqpzDQt7/qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
