---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: default
type: Opaque
stringData:
  SECRET_POSTGRES_USERNAME: "${BOOTSTRAP_SECRET_POSTGRES_USERNAME}"
  SECRET_POSTGRES_PASSWORD: "${BOOTSTRAP_SECRET_POSTGRES_PASSWORD}"
