---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: default
type: Opaque
stringData:
  PUSHOVER_TOKEN: "${BOOTSTRAP_RADARR_TOKEN}"
  RADARR__API_KEY: "${BOOTSTRAP_RADARR_API_KEY}"
  PUSHOVER_USER_KEY: "${BOOTSTRAP_PUSHOVER_KEY}"
  ALEXA_NOTIFICATION_KEY: "${BOOTSTRAP_ALEXA_NOTIFICATION_KEY}"
