---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: default
type: Opaque
stringData:
  PUSHOVER_TOKEN: "${BOOTSTRAP_SONARR_TOKEN}"
  SONARR__API_KEY: "${BOOTSTRAP_SONARR_API_KEY}"
  PUSHOVER_USER_KEY: "${BOOTSTRAP_PUSHOVER_KEY}"
