---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.10.10
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    pspEnable: false
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 10m
        memory: 256Mi
    csi:
      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 50m
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m
      # -- CEPH CSI RBD plugin resource requirement list
      # @default -- see values.yaml
      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m

      # -- CEPH CSI CephFS provisioner resource requirement list
      # @default -- see values.yaml
      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 20m
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m

      # -- CEPH CSI CephFS plugin resource requirement list
      # @default -- see values.yaml
      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 10m
