---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
  KUBE_VIP_ADDR: "${BOOTSTRAP_KUBE_VIP_ADDR}"
  METALLB_LB_RANGE: "${BOOTSTRAP_METALLB_LB_RANGE}"
  METALLB_K8S_GATEWAY_ADDR: "${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}"
  METALLB_INGRESS_ADDR: "${BOOTSTRAP_METALLB_INGRESS_ADDR}"
  NFS_SERVER_ADDRESS: "${BOOTSTRAP_NFS_SERVER}"
  NFS_MOUNT_PATH: "${BOOTSTRAP_NFS_MOUNT_PATH}"
  NFS_USER_ID: "${BOOTSTRAP_NFS_USER_ID}"
  NFS_GROUP_ID: "${BOOTSTRAP_NFS_GROUP_ID}"
  SMB_GROUP_ID: "${BOOTSTRAP_SMB_GROUP_ID}"
